### ISSUE TITLE
Can not download blockchain

### ISSUE THREAD

**Issue by bubudod** [rnicoll/altcoinj#46]
I tried to start download blockchain in testnet. However it just keep throwing exceptions and do not start to download blockchain.
```
2021-02-08 15:50:00.776  INFO 14168 --- [eerGroup Thread] o.b.c.PeerSocketHandler                  : [116.62.229.19]:44556 - java.nio.channels.CancelledKeyException
2021-02-08 15:50:02.774  WARN 14168 --- [eerGroup Thread] o.b.n.ConnectionHandler                  : Error writing message to connection, closing connection

java.nio.channels.CancelledKeyException: null
	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:74) ~[?:?]
	at sun.nio.ch.SelectionKeyImpl.interestOps(SelectionKeyImpl.java:93) ~[?:?]
	at org.bitcoinj.net.ConnectionHandler.setWriteOps(ConnectionHandler.java:106) ~[bitcoinj-core-0.15.6.jar:?]
	at org.bitcoinj.net.ConnectionHandler.writeBytes(ConnectionHandler.java:152) [bitcoinj-core-0.15.6.jar:?]
	at org.bitcoinj.core.PeerSocketHandler.sendMessage(PeerSocketHandler.java:92) [bitcoinj-core-0.15.6.jar:?]
	at org.bitcoinj.core.Peer.ping(Peer.java:1569) [bitcoinj-core-0.15.6.jar:?]
	at org.bitcoinj.core.Peer.ping(Peer.java:1560) [bitcoinj-core-0.15.6.jar:?]
	at org.bitcoinj.core.PeerGroup$12.run(PeerGroup.java:1554) [bitcoinj-core-0.15.6.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask.run(MoreExecutors.java:644) [guava-30.0-android.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51) [bitcoinj-core-0.15.6.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by victoriat31** [comment]
Why is that?
